name: Deploy public folder to GitHub Pages

# Ejecutar cada vez que haya push en main
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar el repo
      - uses: actions/checkout@v3

      # 2️⃣ Desplegar carpeta public a GitHub Pages
      - name: Deploy public folder
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
